#Food++ Configuration
#This configuration defined how much food point and  would player restore
DebugMode= true
Version = 1.0.1
APPLE:
  FoodPoint: 0
  Saturation: 0
BAKED_POTATO:
  FoodPoint: 0
  Saturation: 0
BREAD:
  FoodPoint: 0
  Saturation: 0
CAKE:
  FoodPoint: 0
  Saturation: 0
CAKE_BLOCK:
  FoodPoint: 0
  Saturation: 0
CARROT_ITEM:
  FoodPoint: 0
  Saturation: 0
COOKED_CHICKEN:
  FoodPoint: 0
  Saturation: 0
GRILLED_PORK:
  FoodPoint: 0
  Saturation: 0
COOKED_FISH:
  FoodPoint: 0
  Saturation: 0
COOKIE:
  FoodPoint: 0
  Saturation: 0
GOLDEN_APPLE:
  FoodPoint: 0
  Saturation: 0
GOLDEN_CARROT:
  FoodPoint: 0
  Saturation: 0
MELON:
  FoodPoint: 0
  Saturation: 0
MUSHROOM_SOUP:
  FoodPoint: 0
  Saturation: 0
POISONOUS_POTATO:
  FoodPoint: 0
  Saturation: 0
POTATO_ITEM:
  FoodPoint: 0
  Saturation: 0
PUMPKIN_PIE:
  FoodPoint: 0
  Saturation: 0
RAW_BEEF:
  FoodPoint: 0
  Saturation: 0
RAW_CHICKEN:
  FoodPoint: 0
  Saturation: 0
RAW_FISH:
  FoodPoint: 0
  Saturation: 0
PORK:
  FoodPoint: 0
  Saturation: 0
ROTTEN_FLESH:
  FoodPoint: 0
  Saturation: 0
SPIDER_EYE:
  FoodPoint: 0
  Saturation: 0
COOKED_BEEF:
  FoodPoint: 0
  Saturation: 0